baseURL = 'https://matheuslaidler.github.io'
languageCode = 'pt-BR'
title = 'Github M.Laidler Style'
theme = "github-style-remaster"
#googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

		
[params]
  author = "Matheus Laidler"
  description = "Projeto que auxilia no aprendizado de conteÃºdos via divulgaÃ§Ã£o cientÃ­fica, com materiais sobre o mundo da tecnologia e hacking."
  avatar = "../../images/perfil.jpg" #../../ para possÃ­veis abas q nÃ£o consigam achar a imagem, mas jÃ¡ foi corrigido a maioria diretamente no codigo.
  github = "matheuslaidler"
  facebook = "matheus.laidler"
  twitter = "matheuslaidler"
  linkedin = "laidlervidal"
  instagram = "matheuslaidler"
  #tumblr = "#"
  youtube = "@matheuslaidler" #/channel/UCkFbbZX6TG6eZPugmW32YFA/
  email = "matheuslaidler@protonmail.com"
  url = "https://matheuslaidler.github.io" #se nÃ£o colocar ficarÃ¡ como o link do site raiz
  keywords = "matheus laidler, matheuslaidler, matheus-laidler, mlaidler, ciberseguranÃ§a, wayofsecurity, wayofsec, road2tech, road2technology, acervo de TI, artigos, write ups, blog"
  rss = false
  lastmod = true
  favicon = "images/terminal.png"
  location = "Brazil"
  userStatusEmoji = "ðŸ‘½"	# >_ ðŸ’² ðŸ‘½ ðŸ‡²ðŸ‡± ðŸ˜€		ðŸ’»(laptop)	ðŸ¤–(robo)	ðŸ‘¨â€ðŸ’»(tecnologo)	ðŸ–±ï¸(mouse)	ðŸ–¥ï¸(monitor)	ðŸŒ(globo meridianos)	ðŸ“(pastas)	ðŸ“ƒ(pagina)	ðŸ¤“(nerd)	ðŸ’€(caveira)	ðŸ˜Š(sorriso2)	â¤ï¸(coraÃ§Ã£o)	ðŸ¡(home)	ðŸŽ–ï¸(medalha)	ðŸ˜Ž (oculos)	ðŸ‘»(fantasma)	ðŸ‘½(alien)	ðŸ˜œ	ðŸ™ƒ	ðŸ¤¨	ðŸ˜Œ	ðŸ˜ 	ðŸŽƒ	ðŸ¤™	ðŸ‘‹	âœï¸	ðŸ§ 	ðŸ‘	ðŸ‘€	ðŸ‘Œ	ðŸ§‘	ðŸ•µï¸â€â™‚ï¸	ðŸ‘¨â€ðŸ«	ðŸ‘¤	ðŸ¤µðŸ»	ðŸ•µðŸ»â€â™‚ï¸	â„ï¸	ðŸŒŽ	ðŸ”¥	âŒ¨ï¸	ðŸ’Ž	ðŸ”¬	ðŸ‡²ðŸ‡± ðŸ§ 
  enableGitalk = true
    
  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æŽ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æžœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æžœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  
  [[params.links]] #um icone novo para algo - abaixo do perfil
    title = "Rascunhos"
    href = "https://matheuslaidler.gitbook.io"
	# icon = "images/icone.png" #sem nada => icone padrÃ£o de link => "/images/link.png"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
