baseURL = ''
languageCode = 'pt-BR'
title = 'Hugo Github Style Remaster'
theme = "github-style-remaster"
pygmentsCodeFences = true
pygmentsUseClasses = true

		
[params]
  author = "Matheus Laidler"
  description = "Hugo Remade Theme"
  avatar = "../../images/perfil.jpg"
  github = "matheuslaidler"
  medium = "matheuslaidler"
  gitbook = "matheuslaidler"
  #stackoverflow = "23312896"
  instagram = "matheuslaidler"
  youtube = "/channel/UCkFbbZX6TG6eZPugmW32YFA/"
  gitlab = "matheuslaidler"
  linkedin = "laidlervidal"
  email = "matheuslaidler@protonmail.com"
  url = "https://gitlab.com/matheuslaidler" #se nÃ£o colocar ficarÃ¡ como o link do site raiz
  keywords = "matheus laidler, matheuslaidler, matheus-laidler, mlaidler, hugo, hugo theme, github-style, github style, github style remaster, github hugo theme"
  rss = false
  lastmod = true
  favicon = "images/terminal.png"
  location = "Brazil"
  userStatusEmoji = ">_"	#ğŸ’² ğŸ‘½ ğŸ‡²ğŸ‡± ğŸ˜€		ğŸ’»(laptop)	ğŸ¤–(robo)	ğŸ‘¨â€ğŸ’»(tecnologo)	ğŸ–±ï¸(mouse)	ğŸ–¥ï¸(monitor)	ğŸŒ(globo meridianos)	ğŸ“(pastas)	ğŸ“ƒ(pagina)	ğŸ¤“(nerd)	ğŸ’€(caveira)	ğŸ˜Š(sorriso2)	â¤ï¸(coraÃ§Ã£o)	ğŸ¡(home)	ğŸ–ï¸(medalha)	ğŸ˜ (oculos)	ğŸ‘»(fantasma)	ğŸ‘½(alien)	ğŸ˜œ	ğŸ™ƒ	ğŸ¤¨	ğŸ˜Œ	ğŸ˜ 	ğŸƒ	ğŸ¤™	ğŸ‘‹	âœï¸	ğŸ§ 	ğŸ‘	ğŸ‘€	ğŸ‘Œ	ğŸ§‘	ğŸ•µï¸â€â™‚ï¸	ğŸ‘¨â€ğŸ«	ğŸ‘¤	ğŸ¤µğŸ»	ğŸ•µğŸ»â€â™‚ï¸	â„ï¸	ğŸŒ	ğŸ”¥	âŒ¨ï¸	ğŸ’	ğŸ”¬	ğŸ‡²ğŸ‡± ğŸ§ 
  enableGitalk = true
    
  [params.gitalk]
    clientID = "" # Your client ID 
    clientSecret = "" # Your client secret 
    repo = "" # matheuslaidler.github.io/blog - # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "" #  æ‚¨çš„GitHub ID
    admin = "" #  æ‚¨çš„GitHub ID
    id = "location.pathname" #  æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
